openapi: 3.0.0
info:
  x-skaffolder-id-project: 62c59fcbc97c70218d658baf
  title: webApp
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /utenti:
    post:
      x-skaffolder-id: 62c5a47ac97c70218d658c46
      x-skaffolder-name: create
      x-skaffolder-id-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-resource: Utenti
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - Utenti
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Utenti"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Indirizzo:
                  type: string
                Name:
                  type: string
                Note:
                  type: string
    get:
      x-skaffolder-id: 62c5a47ac97c70218d658c4c
      x-skaffolder-name: list
      x-skaffolder-id-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-resource: Utenti
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - Utenti
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Utenti"
  "/utenti/{id}":
    delete:
      x-skaffolder-id: 62c5a47ac97c70218d658c4d
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-resource: Utenti
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - Utenti
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 62c5a47ac97c70218d658c47
      x-skaffolder-name: get
      x-skaffolder-id-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-resource: Utenti
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - Utenti
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Utenti"
    post:
      x-skaffolder-id: 62c5a47ac97c70218d658c48
      x-skaffolder-name: update
      x-skaffolder-id-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-resource: Utenti
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - Utenti
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Utenti"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Utenti"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Utenti:
      x-skaffolder-id: 62c5a44bc97c70218d658c43
      x-skaffolder-id-db: 62c59fcbc97c70218d658bb0
      x-skaffolder-id-entity: 62c5a44bc97c70218d658c3f
      x-skaffolder-url: /utenti
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        Indirizzo:
          type: string
          x-skaffolder-id-attr: 62c5a44bc97c70218d658c41
          x-skaffolder-type: String
          x-skaffolder-required: true
        Name:
          type: string
          x-skaffolder-id-attr: 62c5a44bc97c70218d658c40
          x-skaffolder-type: String
          x-skaffolder-required: true
        Note:
          type: string
          x-skaffolder-id-attr: 62c5a44bc97c70218d658c42
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - Indirizzo
        - Name
        - Note
  x-skaffolder-db:
    - x-skaffolder-id: 62c59fcbc97c70218d658bb0
      x-skaffolder-name: webApp_db
  x-skaffolder-page:
    - x-skaffolder-id: 62c5a584c97c70218d658c51
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 62c5a47ac97c70218d658c4b
      x-skaffolder-roles: []
    - x-skaffolder-id: 62c5a47ac97c70218d658c45
      x-skaffolder-name: UtentiEdit
      x-skaffolder-url: /utentis/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-services:
        - 62c5a47ac97c70218d658c46
        - 62c5a47ac97c70218d658c48
        - 62c5a47ac97c70218d658c47
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 62c5a47ac97c70218d658c4b
      x-skaffolder-name: UtentiList
      x-skaffolder-url: /users
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 62c5a44bc97c70218d658c43
      x-skaffolder-services:
        - 62c5a47ac97c70218d658c4d
        - 62c5a47ac97c70218d658c4c
        - 62c5a47ac97c70218d658c47
        - 62c5a47ac97c70218d658c48
        - 62c5a47ac97c70218d658c46
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 62c5a47ac97c70218d658c45
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 62c59fccc97c70218d658bbb
      x-skaffolder-name: ADMIN
